source 'https://rubygems.org'

gem 'bootstrap-sass'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem "paperclip", "~> 5.0.0"
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'font-awesome-rails'
gem 'toastr-rails'
gem 'braintree' # payment
gem 'figaro'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
