# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beef5f3be99ebfe635a521d8411f23dae551c02a62432ddbfe8ce9e45d49d9474584334045e6550f56a5606f9d488245bc3c3149a0a5e88fb38eddc65600188f

test:
  secret_key_base: b5b15b3a0c361ba26212c1b657e335d813906eb6b0e5f807d40f1a566fc69cb129c84d0ffde0883d56c1ede54868411d63f6015c048c4ffa0f783982ce1e2d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
